# Generated by Django 4.2.11 on 2024-10-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=10000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('nutriscore', models.CharField(max_length=1)),
                ('product_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('image_url', models.URLField(max_length=500)),
                ('categories', models.ManyToManyField(to='food_selection.category')),
            ],
        ),
    ]
