# Generated by Django 4.2.11 on 2025-01-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_selection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
